# Site wide configuration

title: Separate Strings
description:  "Single String Processing = Poly-Processing (so far called Hexaphonic or Polyphonic Guitars)"
logo: synth.jpg
teaser: light_synth.jpg
locale: en_US
url: //separate-strings.github.io

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Matthias Grob
  web: http://separate-strings.org
  email: help@separate-strings.org
  twitter: separate-strings
  bio: "Single String Processing."
  avatar: bio-photo.jpg # 160x160 px image for author byline
  google:
    plus:
    ad-client: #ca-pub-7328585512091257
    ad-slot: #3049671934
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
